### ISSUE TITLE
Missing "labels" param on "Add labels to an issue"

### ISSUE THREAD

**Issue by wilhelmklopp** [octokit/routes#205]
- endpoint scope: repos
- endpoint name: Add labels to an issue
- route: POST /repos/:owner/:repo/issues/:number/labels
- documentation URL: https://developer.github.com/v3/issues/labels/#add-labels-to-an-issue

### Current specification

https://github.com/octokit/routes/blob/fc9df8d41c248f18972a1baa6c0110227d81b48d/routes/issues/labels/add-labels-to-an-issue.json#L6-L28

### I expected

<details>
  <summary>params is missing "labels"</summary>

```json
"params": [
    {
      "name": "owner",
      "type": "string",
      "required": true,
      "description": "",
      "location": "url"
    },
    {
      "name": "repo",
      "type": "string",
      "required": true,
      "description": "",
      "location": "url"
    },
    {
      "name": "number",
      "type": "integer",
      "required": true,
      "description": "",
      "location": "url"
    },
    {
          "name": "labels",
          "type": "string[]",
          "required": true,
          "location": "body"
        },
  ],
```
</details>

Just came across this while building a routes-powered GitHub App 😬 
I might be getting wrong what the expected version should look like, but this feels like a bug, or something not easily scrapable?

**Comment by gr2m** [comment]
Ah that’s a tricky one, we have to implement a workaround for this somehow. I talked to @kytrinyx about routes that expect an array in the request body root, I think she is looking into making the routes accept a namespace as well, so instead of 

```json
[
  "Label1",
  "Label2"
]
```

you’ll have 

```json
{
  "labels": [
    "Label1",
    "Label2"
  ]
}
```

and then we can list `labels` in a parameters table, too.

In `octokit/rest` I have a `mapTo` property to workaround that: https://github.com/octokit/rest.js/blob/e8a786e9e7f3cf1c5004374409cc269253ae4edc/lib/routes.json#L2769-L2773

I’m not sure if we should add something similar to octokit/routes or if we should wait for it to be resolved on the REST API handlers / documentation

**Comment by gr2m** [comment]
I’ve added the "mapTo" property to octokit/routes via https://github.com/octokit/routes/pull/281
