### ISSUE TITLE
Clarify versioning

### ISSUE THREAD

**Issue by WillAbides** [octokit/routes#308]
I'd like to clarify my understanding of how routes is versioned.

It appears the mechanics are handled by [semantic-release](https://github.com/semantic-release/semantic-release), which creates creates a release for every push to master and sets the version based on commit messages. This is the first I've seen semantic-release, and it looks like a good idea.

After browsing recent release history, breaking changes appear to be changes to the json format and changes to routes that would cause previously successful requests to fail.  Feature changes are either adding routes or route parameters.  Bug fixes appear to be both bug fixes to routes itself and to GitHub's docs.

Also, it appears that the commit messages are manually set and not done automatically based on detected changes.

Let me know if/where I'm wrong above. I would like to use route's version changes as an indicator for setting [octo-cli](https://github.com/octo-cli/octo-cli)'s version.  So if routes increments a minor version, then the octo-cli release that incorporates that routes release will also increment a minor version.

**Comment by gr2m** [comment]
Yeah semantic-release is wonderful, I use it for all my JavaScript Open Source projects, I’d never be able to maintain so many libraries if not for semantic-release to automate all the releases. 

Here is the release process in a nutshell: https://github.com/octokit/rest.js/blob/master/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version I’ll add a section like this to octokit/routes, too. Is that helpful?

In terms of what version to bump, I’d be happy to adapt to your needs with `octo-cli`, too. It’s not that straight forward as it is with normal libraries. For example, [v14.7](https://github.com/octokit/routes/releases/tag/v14.7.0) removed the `mapTo` setting. I would consider that a "fix". But if you want to use the route definition for GitHub enterprise, it would be a breaking change.

In future, I also want to add deprecations to `octokit/routes` when parameters or methods get renamed. I’ll probably use a timestamp so that a consumer like `octokit-cli` or `@octokit/rest` can set a timestamp of their last breaking change and then keep all the deprecations until the next breaking version release. Right now, all these deprecations are maintained in [@octokit/rest/lib/routes.json](https://github.com/octokit/rest.js/blob/16f94f72c218695fdad371737f636960c4ea245c/lib/routes.json) (search for "alias" / "deprecated").

Let me know what you think :)

**Comment by WillAbides** [comment]
It would be go to have that explanation in routes/CONTRIBUTING.md too. Now I know where to find it in rest.js, but the next person might not.

You're right, it seems that versioning isn't straight forward when user interface is a json file that is being used for who-knows-what. It's much easier when you have method signatures to compare. 

After thinking this over, octo-cli might be better off disregarding the routes' version and instead inspect the method signatures in the generated code to determine the version change. If existing arguments are changed, it's a breaking change.  If new, optional arguments are added or if new methods are added, it's a feature change.  If nothing changes, it's just a new build.

I'm not sure that I understand what you're saying about deprecations.  To put a concrete example on it, let's say `GET /applications/grants/:id` changes to `GET /applications/grants/:grant_id` (which routes.json tells me has actually happened).  I think you are proposing that `index.json` would have both `id` and `grant_id` but with `id` marked as deprecated and aliased to `grant_id`.  `octo-cli` and `rest.js` could avoid unnecessary breaking changes by continuing to use `id`.

If that is what you're proposing, it sounds great to me. With a change like `id` -> `grant_id`, octo-cli would probably do a patch that marks `id` deprecated in help and makes it an alias for `grant_id`. I'm not sure we would ever remove `id` unless it somehow conflicted with another parameter (don't see that happening in the grant_id case but maybe others).

**Comment by WillAbides** [comment]
I only noticed this morning that the routes.json you linked to is in rest, not routes (yesterday I thought routes.json was just a file I hadn't noticed before).  Now this makes more sense to me.  I'm still :+1: on the idea.

A side note about the json format: It might be easier to consume if the alias has `"type": "alias"` and `"target": "thread_id"`since I'm already looking at each param's type to determine how to handle it.

**Comment by gr2m** [comment]
In `@octokit/rest` I process aliases first and look for `type` after that

here for methods
https://github.com/octokit/rest.js/blob/16f94f72c218695fdad371737f636960c4ea245c/lib/plugins/endpoint-methods/index.js#L20-L23

here for params:
https://github.com/octokit/rest.js/blob/16f94f72c218695fdad371737f636960c4ea245c/lib/plugins/endpoint-methods/validate.js#L11-L30

**Comment by WillAbides** [comment]
I think this is pretty well clarified.
