### ISSUE TITLE
OpenAPI Reference Object conformance

### ISSUE THREAD

**Issue by SOF3** [octokit/routes#528]
Referring to https://github.com/octokit/routes/blob/master/openapi/api.github.com/index.json

According to OpenAPI 3.0.1 (which this file declares to conform to), Reference Objects are not allowed as a variant of `.paths.{path}.{method}`.

In the section [Path Item Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#path-item-object), `.paths.{path}` can indeed be replaced with a Reference Object, i.e. it is possible to have this:

```json
{
  "openapi": "3.0.1",
  "paths": {
    "/app": {
      "$ref": "operations/apps/get-authenticated.json"
    }
  }
}
```

On the other hand, in the actual Path Item Object values, the `get`, `put`, etc. fields should contain an [Operation Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#operationObject). It does not mention anywhere that an Operation Object can be alternatively a Reference Object.

There are some fields in Operation Object that can be a Reference Object, e.g. `Operation.parameters[]`, `Operation.requestBody`, etc., but Operation Object itself is not allowed to be a Reference Object.

**Comment by SOF3** [comment]
index.json is also invalid according to JSON Schema validators:

![image](https://user-images.githubusercontent.com/19623715/64678734-c240c980-d4ac-11e9-8bc9-a85b56828c77.png)

**Comment by RomanHotsiy** [comment]
@gr2m actually @SOF3 is right... I work with OpenAPI for years and I just didn't notice that 🙈 This is a bit unexpected I would say. I spent some time searching issues in the OpenAPI spec that can explains the reason for that behaviour but with no success yet.

Although, most `$ref` resolvers in the wild are not OpenAPI aware so there should be no issues using this with tooling (at least in JS ecosystem). 

The core issue can be fixed if we migrate all operations of the same path to a separate JSON file and reference them from index files instead. The downside is the path item files will be bigger.

It looks like changing the format will require lots of work at this point because the mapping to filenames is mostly manual ([`getIdName`](https://github.com/octokit/routes/blob/eb1fb352c8690c063f2c3227664771b784622b66/lib/openapi.js#L83))

If this is causing problems to @SOF3 they can use bundled OAS definitions from [Releases](https://github.com/octokit/routes/releases) assets.

@gr2m you may add a note to the readme to communicate this issue.

**Comment by gr2m** [comment]
Maybe this is not a problem at all? I think we will probably end up distributing de-referenced files anyway.

But good call on adding a note to the README

@SOF3 starting with version 23, the package in the npm registry already only includes the dereferenced files: https://unpkg.com/browse/@octokit/routes@23.0.0/. The files are attached to the release on GitHub, too: https://github.com/octokit/routes/releases/tag/v23.0.0
