### ISSUE TITLE
Format routes using Swagger JSON format

### ISSUE THREAD

**Issue by philschatz** [octokit/routes#55]
Is there value in having the `routes.json` follow the https://swagger.io format? This might help document the REST API and allow people to build libraries. Currently, the JSON format is pretty close, describing the URL with placeholders, and parameters.

[Example of a `swagger.yml` file](https://github.com/Connexions/cnx-press/blob/master/press/views/api-docs/swagger.yaml)

**Comment by gr2m** [comment]
I have no oppinion on the format, if it would make it easier for folks to build cool things with it, awesome :) I also prefer the path format with the URL Template spec-compliant `'/contents/{id}'` instead of `'/contents/:id'`, I’ve reached out to the documentation folks to change that in the API docs, too.

If you’d like to give it a go please go ahead :) Would you do yaml? Or can we keep it in JSON?

**Comment by gr2m** [comment]
sounds all good! And no rush, I’ll be on vacation most of April 2-20 :) Thanks!

**Comment by gr2m** [comment]
we started working on #168, I think we can close this issue in favor of that?
