### ISSUE TITLE
enum format

### ISSUE THREAD

**Issue by gr2m** [octokit/routes#56]
Example: https://github.com/octokit/routes/blob/fe0a25467e167c54628c2072884911a50c93269a/routes/pulls/list-pull-requests.json#L21-L26

In [`octokit/rest.js/lib/routes.json`](https://github.com/octokit/rest.js/blob/f8f0e8131d3eb2b9d4a795e6a004845915c856fa/lib/routes.json#L5089-L5094), we currently do

```json
          "type": "string",
          "enum": [
            "merge",
            "squash",
            "rebase"
          ],
``` 

I think the latter format is better, because it tells the type of the value, the `enum` is just an addition. I’ve no opinion on wether to call the array key `enum` or `options`

Any thoughts @philschatz?

**Comment by gr2m** [comment]
Maybe while talking about `"type"`, I do prefer e.g. `"string[]"` over `"array"`. In comparison to `octokit/rest.js/lib/routes.json` we also do `"type": "object"` instead of `"type": "json"` which I think is fine.

**Comment by gr2m** [comment]
here is an issue/PR with a failing test to work on this: https://github.com/octokit/routes/issues/62

**Comment by philschatz** [comment]
`type: "string", enum: [...]` seems fine to me. Having `type:"enum", options: [...]` does not really save anything and it is nice to record that the field is actually a string.

The only downsides of using `type: "string[]"` (rather than a field like `isArray: true`) that I can think of are:

1. the string will need to be parsed in order to determine whether the return type is an Array
2. more complex return types like `Repository[]` may be difficult to describe

To the 2nd concern: if a JSON Schema is provided for the return type, I am not sure how it would be described in this file. I can try creating a Swagger JSON (#55) of the routes to see if it is a problem.

**Comment by gr2m** [comment]
Okay so let’s move forward with at least the change of `type: "enum"` to `type: "string"`. 

The current v3 documentation does only have two types of arrays for parameters, `string[]` and `number[]`, maybe that’s simple enough? I’m okay with `isArray: true`, we’d need to adapt the PR here accordingly: https://github.com/octokit/routes/pull/77. Maybe let’s continue discussion about array types there, as it’s out of the original scope of this issue?
